# Stage 1: Build React app
FROM node:18-alpine AS builder

RUN addgroup -S trackr-group && adduser -S trackr-user -G trackr-group
WORKDIR /app

COPY --chown=trackr-user:trackr-group package*.json ./
RUN npm install

COPY --chown=trackr-user:trackr-group . .

RUN npm run build

RUN chown -R trackr-user:trackr-group /app

USER trackr-user

FROM nginx:alpine

RUN rm -rf /usr/share/nginx/html/*

COPY --from=builder /app/dist /usr/share/nginx/html

COPY ./certs/localhost.cert /etc/nginx/certs/localhost.cert
COPY ./certs/localhost.key /etc/nginx/certs/localhost.key

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
