apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.client.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.client.name }}
spec:
  replicas: {{ .Values.client.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.client.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.client.name }}
    spec:
      containers:
        - name: {{ .Values.client.name }}
          image: {{ .Values.client.image }}
          ports:
            - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.server.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.server.name }}
spec:
  replicas: {{ .Values.server.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.server.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.server.name }}
    spec:
      containers:
        - name: {{ .Values.server.name }}
          image: {{ .Values.server.image }}
          ports:
            - containerPort: 3001
          env:
            - name: NODE_ENV
              value: {{ .Values.server.service.env.NODE_ENV | quote }}
