apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-ingress-controller-config
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx

data:
  http-snippet: |
    types {
      text/html html;
      text/css css;
      text/xml xml;
      image/gif gif;
      image/jpeg jpeg jpg;
      application/javascript js;
      application/json json;
      application/font-woff woff;
      application/font-woff2 woff2;
      application/vnd.ms-fontobject eot;
      application/x-font-ttf ttf;
      application/x-font-opentype otf;
      image/png png;
      image/svg+xml svg svgz;
    }
