{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: trackr-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tlsSecretName | default "trackr-tls" }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /api/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: trackr-server-service
                port:
                  number: 3001
          - path: /(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: trackr-client-service
                port:
                  number: 80
{{- end }}
