apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.clientname }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.client.name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.servername }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.server.name }}
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: ClusterIP
