namespace: trackr
client:
  image: samwilk18/job-trackr-client:latest
  replicaCount: 2
  service:
    port: 80
server:
  image: samwilk18/job-trackr-server:latest
  replicaCount: 2
  service:
    port: 3001
    env:
      NODE_ENV: production
ingress:
  enabled: true
  host: localhost
  tlsSecretName: trackr-tls
