name: Docker Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install OpenSSL
        run: sudo apt-get update && sudo apt-get install -y openssl

      - name: Generate Certificates
        run: |
          chmod +x ./generate-certs.sh
          ./generate-certs.sh server server
          ./generate-certs.sh localhost client
          ./generate-certs.sh localhost postgres

      - name: Upload Certificates as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ssl-certificates
          path: |
            ./server/certs/
            ./client/certs/
            ./postgres/certs/
          retention-days: 1

      - uses: actions/setup-node@v1
        with:
          node-version: 22
      - run: |
          cd client
          npm i
          npm run build

  build-client-docker:
    runs-on: ubuntu-latest
    needs: build-ui
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/job-trackr-client:latest
          context: ./client

  build-server-docker:
    runs-on: ubuntu-latest
    needs: build-ui
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/job-trackr-server:latest
          context: ./server
